AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for S3 bucket with data lake structure'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name
  
  BucketPrefix:
    Type: String
    Default: data-warehouse
    Description: Prefix for bucket name

Resources:
  # S3 Bucket for Data Lake
  DataLakeBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub '${BucketPrefix}-${Environment}-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: TransitionOldData
            Status: Enabled
            Transitions:
              - TransitionInDays: 90
                StorageClass: STANDARD_IA
              - TransitionInDays: 180
                StorageClass: GLACIER
            NoncurrentVersionTransitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
            NoncurrentVersionExpirationInDays: 90
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: DataLake

  # Bucket Policy for Cross-service access
  DataLakeBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DataLakeBucket
      PolicyText:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowGlueAccess
            Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action:
              - 's3:GetObject'
              - 's3:PutObject'
              - 's3:DeleteObject'
            Resource: !Sub '${DataLakeBucket.Arn}/*'
          - Sid: AllowRedshiftSpectrum
            Effect: Allow
            Principal:
              Service: redshift.amazonaws.com
            Action:
              - 's3:GetObject'
              - 's3:ListBucket'
            Resource:
              - !GetAtt DataLakeBucket.Arn
              - !Sub '${DataLakeBucket.Arn}/*'

  # Raw Data Prefix
  RawDataMarker:
    Type: AWS::S3::Object
    DeletionPolicy: Delete
    Properties:
      Bucket: !Ref DataLakeBucket
      Key: raw/
      Body: ''

  # Processed Data Prefix
  ProcessedDataMarker:
    Type: AWS::S3::Object
    DeletionPolicy: Delete
    Properties:
      Bucket: !Ref DataLakeBucket
      Key: processed/
      Body: ''

  # Curated Data Prefix
  CuratedDataMarker:
    Type: AWS::S3::Object
    DeletionPolicy: Delete
    Properties:
      Bucket: !Ref DataLakeBucket
      Key: curated/
      Body: ''

  # Logs Prefix
  LogsMarker:
    Type: AWS::S3::Object
    DeletionPolicy: Delete
    Properties:
      Bucket: !Ref DataLakeBucket
      Key: logs/
      Body: ''

Outputs:
  DataLakeBucketName:
    Description: Name of the Data Lake S3 bucket
    Value: !Ref DataLakeBucket
    Export:
      Name: !Sub '${AWS::StackName}-bucket-name'

  DataLakeBucketArn:
    Description: ARN of the Data Lake S3 bucket
    Value: !GetAtt DataLakeBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-bucket-arn'
