AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for RDS PostgreSQL database'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name

  DBInstanceClass:
    Type: String
    Default: db.t3.micro
    AllowedValues: [db.t3.micro, db.t3.small, db.t3.medium, db.m5.large, db.m5.xlarge]
    Description: RDS instance type

  DBName:
    Type: String
    Default: warehousedb
    MinLength: 1
    MaxLength: 64
    Description: Database name

  DBUsername:
    Type: String
    Default: admin
    MinLength: 1
    MaxLength: 16
    NoEcho: true
    Description: Master username for database

  DBPassword:
    Type: String
    MinLength: 8
    MaxLength: 41
    NoEcho: true
    Description: Master password for database (min 8 characters)

  AllocatedStorage:
    Type: Number
    Default: 20
    MinValue: 20
    MaxValue: 65536
    Description: Allocated storage in GB

  VpcId:
    Type: String
    Description: VPC ID for security group
    Default: ''

Conditions:
  CreateVpcResources: !Not [!Equals [!Ref VpcId, '']]

Resources:
  # Security Group for RDS
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for RDS PostgreSQL
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0
          Description: Allow PostgreSQL access
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: RDS

  # DB Subnet Group (if VPC provided)
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Condition: CreateVpcResources
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS
      SubnetIds:
        - !Ref VpcId
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # RDS PostgreSQL Instance
  RDSInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    Properties:
      Engine: postgres
      EngineVersion: '14.7'
      DBInstanceIdentifier: !Sub 'warehouse-db-${Environment}'
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref AllocatedStorage
      StorageType: gp2
      StorageEncrypted: true
      DBName: !Ref DBName
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      BackupRetentionPeriod: 7
      PreferredBackupWindow: '03:00-04:00'
      PreferredMaintenanceWindow: 'mon:04:00-mon:05:00'
      MultiAZ: !If [CreateVpcResources, true, false]
      EnableCloudwatchLogsExports:
        - postgresql
      EnableIAMDatabaseAuthentication: true
      DeletionProtection: false
      EnableDeletionProtection: false
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: DataWarehouse

  # RDS Enhanced Monitoring Role
  RDSMonitoringRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: monitoring.rds.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole'

  # DB Parameter Group
  RDSParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: Parameter group for PostgreSQL
      Family: postgres14
      Parameters:
        log_statement: 'all'
        log_min_duration_statement: 1000
      Tags:
        - Key: Environment
          Value: !Ref Environment

Outputs:
  RDSEndpoint:
    Description: RDS Database endpoint
    Value: !GetAtt RDSInstance.Endpoint.Address
    Export:
      Name: !Sub '${AWS::StackName}-endpoint'

  RDSPort:
    Description: RDS Database port
    Value: !GetAtt RDSInstance.Endpoint.Port
    Export:
      Name: !Sub '${AWS::StackName}-port'

  RDSDatabase:
    Description: RDS Database name
    Value: !Ref DBName
    Export:
      Name: !Sub '${AWS::StackName}-database'

  RDSSecurityGroupId:
    Description: RDS Security Group ID
    Value: !Ref RDSSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-sg-id'
